# Config file of MOT17 dataset

DATASET_ROOT: '/data/MOT_Datasets/AntiUAV-MultiUAV-tr50-val50'  # your dataset root
SPLIT: val
CATEGORY_NAMES:  # category names to show
  - 'drone'

CATEGORY_DICT:
  0: 'drone'

CERTAIN_SEQS:
  -
IGNORE_SEQS:  # Seqs you want to ignore
  -

YAML_DICT: ''  # NOTE: ONLY for yolo v5 model loader(func DetectMultiBackend)
